# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'udonkoapps2018-desktop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for udonkoapps2018-desktop

end

target 'udonkoapps2018-mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for udonkoapps2018-mobile
  pod 'Firebase/Core'

end

#target 'WatchKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WatchKit

#end

#target 'WatchKit Extension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WatchKit Extension

#end
